package com.planning.web;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.planning.dao.UserDAO;
import com.planning.model.RightsStatus;
import com.planning.model.User;

@Controller
@RequestMapping(path = "/user")
public class UserController {

//	@Autowired // This means to get the bean called userService which is auto-generated by
//				// Spring, we will use it to handle the data
//	private UserDAO userDAO; 

	@GetMapping(path = "/add") // Map ONLY GET Requests
	public @ResponseBody String addNewUser(@RequestParam String firstName, @RequestParam String lastName) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		User n = new User(RightsStatus.BASIC_USER);
		
		n.setFirstName("Louis");
		n.setLastName("Guinard");
		//userDAO.save(n);
		return "Saved";
	}

//	@GetMapping(path = "/all")
//	public ModelAndView testUserAll() {
//		return new ModelAndView("user", "userList", getAllUsers());
//	}
//	
//	public @ResponseBody Iterable<User> getAllUsers() {
//		// This returns a JSON or XML with the users
//		return userDAO.findAll();
//	}

}
